# Numpy 패키지 --------------------------------------------

- pandas에서 데이터를 저장 및 처리에 사용되는 패키지

- 외부 패키지로 반드시 설치 필요

- 고속 데이터 처리, 수치 계산 수행 패키지

- 머신러닝/딥러닝용 패키지 Scikit_lern, Tensorflow, PyTorch, Keras 등등에서도 내부 데이터 저장 및 숯치 계산에 사용되는 패키지

- [중요] 동일한 데이터 타입의 데이터를 저장하는 배열(Array) 타입!

- 설치: !pip install numpy

In [38]:
# 모듈 버전 확인 및 버전 확인
import numpy as np

np.__version__

'1.23.0'

In [39]:
# ndarray 객체 생성 하기 ---> numpy.array()

arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [40]:
type(arr1)

numpy.ndarray

In [41]:
# ndarray 객체 속성 확인하기 ------------------------------
# 객체변수명.속성명
# ndim : 차원 (예: 1,2,3,...)
# shpae : 형태 (예: (갯수,), (행, 열),(면, 행, 열))
# dtype : 데이터 타입
# itemsize : 배열 요소의 바이트 크기
# size : 배열 요소 갯수

print(arr1.ndim, arr1.shape, arr1.dtype, arr1.itemsize, arr1.size, sep='\n')

1
(3,)
int32
4
3


In [42]:
# 배열의 요소 즉 아이템, 원소 접근하기---------------------------
# 0 - base 인덱스 자동 지정 => 객체변수명[ 인덱스 ]

print(f'객체변수명 arr1    => {arr1}')
print(f'객체변수명 arr1[0] => {arr1[0]}')
print(f'객체변수명 arr1[1] => {arr1[1]}')

객체변수명 arr1    => [1 2 3]
객체변수명 arr1[0] => 1
객체변수명 arr1[1] => 2


In [43]:
# 모든 값을 0 으로 채워서 ndarray 객체 생성 함수 => ones()
arr2 = np.array([1,1,1,1])
arr2 = np.ones(4, dtype=np.int16)
arr2

array([1, 1, 1, 1], dtype=int16)

In [44]:
print(arr2.ndim, arr2.shape, arr2.dtype, arr2.itemsize, arr2.size, sep='\n')
print(f'객체변수명 arr2    => {arr2}')
print(f'객체변수명 arr2[0] => {arr2[0]}')
print(f'객체변수명 arr2[1] => {arr2[1]}')

1
(4,)
int16
2
4
객체변수명 arr2    => [1 1 1 1]
객체변수명 arr2[0] => 1
객체변수명 arr2[1] => 1


In [45]:
# 초기화하지 않고 ndarray 객체 생성 => numpy.empty()
arr3 = np.empty((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
# 2차원 형태의 ndarray 객체 생성
arr4= np.array([[2,3,4],[1,2,3]])
arr4

array([[2, 3, 4],
       [1, 2, 3]])

In [48]:
arr4.shape, arr4.ndim

((2, 3), 2)

In [53]:
arr5=arr4.flatten()

In [54]:
arr5.shape, arr5.ndim

((6,), 1)

In [59]:
# 1차원 => 다른 차원으로 변경 reshape()
arr6 = arr5.reshape((3,2))
arr6

array([[2, 3],
       [4, 1],
       [2, 3]])

In [57]:
arr6 = arr5.reshape((1,3,2))
arr6

array([[[2, 3],
        [4, 1],
        [2, 3]]])

In [58]:
arr7=arr6.flatten()
arr7.shape, arr7.ndim

((6,), 1)

In [60]:
# 차원/형태 변환 = reshape(-1,n), reshape(n,-1)
arr8 = np.arange(8)
arr8

array([0, 1, 2, 3, 4, 5, 6, 7])

In [61]:
arr9=arr8.reshape(-1,2)
arr9

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [63]:
arr9=arr8.reshape(2,-1)
arr9

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [64]:
# 변형할 행렬 갯수가 모자라면 불가능.
arr9 = arr8.reshape(-1,3) 
arr9

ValueError: cannot reshape array of size 8 into shape (3)